### ISSUE TITLE
Create the skeleton for the encryption and decryption controllers

### ISSUE THREAD

**Issue by simonjaeger** [simonjaeger/encryption-service#1]
Create two new controllers in the project, under the Controllers folders. 

These two controllers will help us encrypt and decrypt incoming strings using a key.

1. Add the controllers as an "API Controller Class". Name them: EncryptController and DecryptController.
1. Create one simple GET method in both of the controllers accepts two parameters from the URL. Name them data and key.

We will use this as the skeleton. The success criteria for these two controllers is to be able to call the service as such:
localhost:[PORT]/api/encrypt?data=hello&key=mykey
localhost:[PORT]/api/decrypt?data=sdfsdasd&key=mykey

No actual encrypt or decrypt logic is needed for this item. This is just to get the calls working.

**Comment by buzzfrog** [comment]
I'll look into this

**Comment by simonjaeger** [comment]
@buzzfrog Related. We can focus on this later: https://github.com/simonjaeger/encryption-service/issues/4
