### ISSUE TITLE
Add a testing framework and sample

### ISSUE THREAD

**Issue by simonjaeger** [simonjaeger/encryption-service#2]
Not a priority task. If there are other tasks available, focus on them unless you really want to take this one. 

1. Add a testing framework of your choice. 
1. Add a sample test to ensure the testing works.
1. Create a TESTING.md file with the steps needed to test new functionality (so that others can understand how to use it).

**Comment by krist00fer** [comment]
Anyone working on this, or can you please assign this to me?

**Comment by krist00fer** [comment]
I'm confused. Is this a focused task or not?!?!?!

**Comment by krist00fer** [comment]
Working on it!

**Comment by simonjaeger** [comment]
Thank you!
